image: julia:1.6

alltests:
  script:
    - apt-get update
    - apt-get -y install git
    - julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
    - cd test
    - mkdir data
    - cd data
    - git clone https://gitlab.com/mistguy/tbdata.git
    - mv tbdata/* .
    - cd ../..
    - julia -e 'using Pkg; Pkg.test("Hop", coverage=true)'
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; cl, tl = get_summary(process_folder()); println("(", cl/tl*100, "%) covered")'

pages:
  script:
    - apt update
    - apt install --assume-yes make gcc git
    - julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
    - julia -e 'using Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
    - cd docs/
    - mv build ../public/
  artifacts:
    paths:
      - public
  only:
    - master
